version: '3.2'

volumes:
  pg-data: {}
  redis-data: {}
  tmp-data: {}

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    user: "${APP_UID:-10001}:${APP_GID:-10001}"
    environment:
      PS1: '\[\033[1;32m\]\[\033[1;36m\][\u@\h] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
      HOME: /tmp
      APP_DEBUG: 'true'
      APP_ENV: local
      REDIS_HOST: redis
      REDIS_PASSWORD: redis_password
      DB_HOST: postgres
      DB_DATABASE: forge
      DB_USERNAME: forge
      DB_PASSWORD: forge
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - tmp-data:/tmp:rw
      - .:/app:rw
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    <<: *app
    command: rr serve -c .rr.local.yaml
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q "http://127.0.0.1:8082/health?plugin=http&plugin=rpc"']
      interval: 2s
      timeout: 2s

  queue:
    <<: *app
    command: php /app/artisan queue:work --memory=256 --sleep=1

  cron:
    <<: *app
    command: supercronic /etc/supercronic/laravel # it runs artisan schedule:run

  postgres:
    image: postgres:13.2-alpine # Image page: <https://hub.docker.com/_/postgres>
    environment:
      POSTGRES_DB: forge
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: forge
    volumes:
      - pg-data:/var/lib/postgresql/data:rw
    ports:
      - 5432/tcp
    healthcheck: # Healthcheck docs: <https://docs.docker.com/engine/reference/builder/#healthcheck>
      test: ['CMD-SHELL', 'pg_isready -U forge']
      interval: 2s
      timeout: 5s

  redis:
    image: redis:6.0.9-alpine # Image page: <https://hub.docker.com/_/redis>
    command: redis-server --requirepass redis_password
    volumes:
      - redis-data:/data:rw
    ports:
      - 6379/tcp
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 2s
      timeout: 5s
