# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Setup PHP with all Dependencies
description: Setup PHP and install all composer dependencies dependencies (using caching)

inputs:
  php-version:
    description: 'Required PHP version'
    required: true
    default: '8.0'

runs:
  using: "composite"
  steps:
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 # Action page: <https://github.com/shivammathur/setup-php>
      with:
        php-version: ${{ inputs.php-version }}

    - name: Get Composer Cache Directory # Docs: <https://git.io/JfAKn#php---composer>
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      shell: bash

    - name: Cache dependencies # Docs: <https://git.io/JfAKn#php---composer>
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.setup }}-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer update -n --prefer-dist --no-progress --ansi && composer info
      shell: bash
